---
namespace: zalenium
app_name: zalenium

app_params:
  ZALENIUM_MEMORY_LIMIT: "2Gi"
  ZALENIUM_CPU_LIMIT: "1000m"
  VIDEOS_STORAGE_SIZE: "10G"
  AGENT_CPU_REQUEST: "100m"
  AGENT_CPU_LIMIT: "1000m"
  AGENT_MEMORY_REQUEST: "1Gi"
  AGENT_MEMORY_LIMIT: "2Gi"


openshift_cluster_content:
- object: Environment Setup
  content:
  - name: Create Projects
    template: "{{ inventory_dir }}/../.openshift/templates/projects.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace }}"
    tags:
      - project
- object: deployments
  content:
  - name: Zalenium
    template: "{{ inventory_dir }}/../.openshift/templates/zalenium-deployment.yml"
    params_from_vars: "{{ app_params }}"
    namespace: "{{ namespace }}"
